### ISSUE TITLE
Set up staging server

### ISSUE THREAD

**Issue by sergeyradkevich** [VolodymyrTymtsiv/TaDa#2]
https://devcenter.heroku.com/articles/getting-started-with-java#introduction

https://devcenter.heroku.com/articles/deploying-java

**Comment by sergeyradkevich** [comment]
Hey guys, let's work on this before creation of a todo item user story please.

**Comment by VolodymyrTymtsiv** [comment]
Here two links **tada-staging-server** and **production-service**:
https://tada-staging-server.herokuapp.com

https://production-service.herokuapp.com

Please check whether all good, if good close the issue or let know that all is well.

**Comment by sergeyradkevich** [comment]
I would name production in similar manner as staging: `tada-prod-server`.

**Comment by sergeyradkevich** [comment]
@VolodymyrTymtsiv I would like to see changes you made so the deployment became possible + updated readme. Would you send them via pull request?

**Comment by ShAndriy** [comment]
New links on heroku:

https://tada-prod-server.herokuapp.com
https://tada-staging-server.herokuapp.com

**Comment by sergeyradkevich** [comment]
Thanks, @ShAndriy. So I'm expecting for a pull request that covers any changes you guys made in order to deploy the app to Heroku.

**Comment by sergeyradkevich** [comment]
Changes are covered within #4
